services:
  urlshortener:
    image: urlshortener:latest
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - redis
  redis:
    container_name: url_shortener-redis
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    labels:
      amplicode.image: redis
volumes:
  redis_data:
