services:
  urlshortener:
    container_name:  urlshortener-1
    image: anseranser/urlshortener:latest
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - redis
  redis:
    container_name: urlshortener-redis
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    labels:
      amplicode.image: redis
  postgres:
    image: postgres:16.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secret
      POSTGRES_DB: urlshortener
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    profiles:
      - prod
volumes:
  redis_data:
  postgres_data:
